### ISSUE TITLE
Some bugs in the code.

### ISSUE THREAD

**Issue by ns-ask** [tianyizhou/DIHCL#1]
Hi, 
Thanks for the awesome work.
I was trying to reproduce the results. I cloned the code on my local system and got a few "import" errors and some minor bugs in the code. I've listed some of them below. Can you please take a look?
In dihcl.py file:
     line 33: import models.cifar as models.
     line 448: k is unknown. (I think it should be k0, right?)

**Comment by tianyizhou** [comment]
Thanks for pointing out the bugs! I just checked in a new version, which can successfully run on my machine now.
